# Generated by Django 5.0.3 on 2024-03-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouses')),
            ],
        ),
    ]
