# Generated by Django 5.0.3 on 2024-03-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_numerator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmaterials',
            unique_together={('product_id', 'material')},
        ),
    ]
