# Generated by Django 5.0.3 on 2024-03-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_alter_productmaterials_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numerator',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
    ]
