# Generated by Django 5.0.3 on 2024-03-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_rename_warehouse_id_numerator_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerator',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
