# Generated by Django 5.0.3 on 2024-03-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_alter_numerator_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerator',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
